version: '3.1'

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis-data:/data
    command: redis-server --appendonly yes

  redis-ui:
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
    environment:
      - REDIS_URI=redis://redis:6379
